### ISSUE TITLE
NPE at org.spring.tools.boot.java.ls.java.ClasspathListener.sendClasspathCommand

### ISSUE THREAD

**Issue by gayanper** [gayanper/sts4#4]
Happens when closing the file and soon as it it open while the LS is starting up.
```java.lang.NullPointerException
	at org.spring.tools.boot.java.ls.java.ClasspathListener.sendClasspathCommand(ClasspathListener.java:127)
	at org.spring.tools.boot.java.ls.java.ClasspathListener.register(ClasspathListener.java:55)
	at org.spring.tools.boot.java.ls.StsLanuageClient.lambda$addClasspathListener$4(StsLanuageClient.java:112)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by gayanper** [comment]
java.lang.NullPointerException
	at org.spring.tools.boot.java.ls.java.ClasspathListener.sendClasspathCommand(ClasspathListener.java:140)
	at org.spring.tools.boot.java.ls.java.ClasspathListener.register(ClasspathListener.java:60)
	at org.spring.tools.boot.java.ls.StsLanuageClient.lambda$addClasspathListener$4(StsLanuageClient.java:112)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
